
Vagrant.configure("2") do |config|
  config.vm.box = "trusty32"
  config.vm.host_name = "eseg-app"
  config.vm.network :forwarded_port, host: 8100, guest: 8100

  Vagrant.configure("2") do |config|
    config.vm.provision "shell", path: "bootstrap.sh"
  end
end
