version: 1.0
disable_existing_loggers: False
formatters:
    simple:
        format: "%(asctime)s - [%(levelname)s] %(name)s:%(lineno)d : %(message)s"


handlers:
    console:
        class: logging.StreamHandler
        stream: ext://sys.stdout
        formatter: simple

    info_file_handler:
        class: logging.handlers.RotatingFileHandler
        filename: terrapin_server/logs/info.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf-8
        formatter: simple

    error_file_handler:
        class: logging.handlers.RotatingFileHandler
        filename: terrapin_server/logs/error.log
        maxBytes: 10485760
        backupCount: 20
        encoding: utf-8
        formatter: simple

loggers:
    requests:
        level: ERROR

root:
    level: DEBUG
    handlers: [console, info_file_handler, error_file_handler]
